//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhaSachEntities : DbContext
    {
        public QuanLyNhaSachEntities()
            : base("name=QuanLyNhaSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoThang> BaoCaoThangs { get; set; }
        public virtual DbSet<HoaDonBanSach> HoaDonBanSaches { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuThutien> PhieuThutiens { get; set; }
        public virtual DbSet<Quydinh> Quydinhs { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<ThongTinBaoCaoThang> ThongTinBaoCaoThangs { get; set; }
        public virtual DbSet<ThongTinHoaDon> ThongTinHoaDons { get; set; }
        public virtual DbSet<ThongTinPhieuNhap> ThongTinPhieuNhaps { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
