//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quydinh
    {
        public int Id { get; set; }
        public Nullable<int> Nhaptoithieu { get; set; }
        public Nullable<int> Sachtontoithieu_Nhap { get; set; }
        public Nullable<int> Sachtontoithieu_Ban { get; set; }
        public Nullable<int> TienNo { get; set; }
        public Nullable<int> Phieuthutien { get; set; }
    }
}
