//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinPhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinPhieuNhap()
        {
            this.ThongTinHoaDons = new HashSet<ThongTinHoaDon>();
        }
    
        public int Id { get; set; }
        public int IdSach { get; set; }
        public int IdPhieunhap { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> DonGiaBan { get; set; }
        public string Status { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual Sach Sach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinHoaDon> ThongTinHoaDons { get; set; }
    }
}
