//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinBaoCaoThang
    {
        public int Id { get; set; }
        public int IdBaoCao { get; set; }
        public int IdSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> Tondau { get; set; }
        public Nullable<int> Soluongban { get; set; }
        public Nullable<int> Soluongnhap { get; set; }
        public Nullable<int> Toncuoi { get; set; }
    
        public virtual BaoCaoThang BaoCaoThang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
